### ISSUE TITLE
Wrong image name in readme 

### ISSUE THREAD

**Issue by byrnedo** [scullxbones/docker_grafana_statsd_elk#1]
I had to replace the underscores with dashes to be able to pull this from the docker registry. 

Thanks for the image!

**Comment by scullxbones** [comment]
Great, I'm happy it could help you out!

Although I looked at the readme and the docker pull command there uses hyphens and looks correct.  Was it `docker pull` you were having trouble with?

**Comment by byrnedo** [comment]
nah, it was the `run` command. 

```
docker run -d -p 80:80 -p 81:81 -p 8125:8125/udp --name grafana scullxbones/docker_grafana_statsd_elk
```

**Comment by scullxbones** [comment]
Ah!  Got it.  Thanks!

**Comment by byrnedo** [comment]
no problem!
